PrunaAI/pruna

- README.md
This PR fixes incorrect links in the Readme pointing to the latest version of the Pruna Documentation instead of stable.
#16 
Verified the Readme on the branch on Github.
None.
> fix: readme links pointing to latest instead of stable

- CODE_OF_CONDUCT.md
- docs/contributions/how_to_contribute.rst
This PR adds the code of conduct file as recognized by Github.com to the repository. I took the code of conduct template from Code Covenant, which seems to be broadly adapted in other OSS repositories.
None.
Checked preview on Github for this branch.
None.
> docs: add code of conduct

- README.md
This PR removes two incorrect checks in the algorithm overview (for Periodic Caching and HYPER) .
Verified the Readme on the branch on Github.
None.
> fix: remove two incorrect checks from the algorithm overview in the README

- docs/tutorials/diffusion_quantization_acceleration.ipynb
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/quantization/hqq_diffusers.py
- src/pruna/engine/load.py
- src/pruna/engine/save.py
- src/pruna/smash.py
- tests/algorithms/test_combinations.py
This PR enables the combination of `torch_compile` and `hqq_diffusers`. This allows the speedup of hqq quantized models in all precisions. This means that we can accelerate any diffusion model after quantization!
You can use it by simply defining the following config:
```
from pruna import SmashConfig
smash_config = SmashConfig()
smash_config['compiler'] = 'torch_compile'
smash_config['quantizer'] = 'hqq_diffusers'
```
This PR also includes many fixes to hqq_diffusers save/load functions. They were only working in 1/3 usecase (transformer-based models).
None.
2 unit tests added that pass (1 unet-based and 1 transformer-based). Tutorial notebook added as well that is also passing.
This can also be extended to LLMs through the `hqq` method but is out of this scope of this PR.
| Model …
> feat: enable combination of torch_compile and hqq_diffusers

- src/pruna/algorithms/compilation/c_translate.py
This PR changes the path used to detect the cudnn binairies available for CTranslate compilation.
This solves a failing test in the nightly tests environment.
> fix: fix cudnn libs path in CTranslate compiler

- .github/workflows/installation.yaml
This PR adds workflows to check the installation of `pruna` on various OS and Python versions to avoid issues like #21 in the future. I am open for discussion on this but generally felt like this is not something that should happen on every commit, but rather on dispatch when the PR necessitates it and once as a sanity check when merging to main.
Avoid #21 in the future
Ran the workflows on this PR. Currently Python 3.12 on ubuntu is failing which is intended, the rest pass.
None.
> ci: add installation tests for all supported OS and python versions

- docs/utils/gen_docs.py
- pyproject.toml
- src/pruna/algorithms/quantization/gptq_model.py
- src/pruna/engine/handler/handler_utils.py
- tests/algorithms/testers/quantization.py
AutoGPTQ is now deprecated. This PR switches our GPTQ algorithm to gptqmodel instead.
autogptq already caused problems with supporting python 3.12.
integration test still runs.
I did not investigate the extent of the new repo. This is only to make the switch. We might be able to find some nice speedups with some investigations.
> feat: switch autogptq to gptqmodel

- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/quantization/huggingface_diffusers_int8.py
- tests/algorithms/test_combinations.py
Small PR that enable the combination of `diffusers_int8` quantizer and `torch_compile` for diffusers model.
The change in the code is minimal, but the results are interesting:
- following the previous work on HQQ (#23), we quantize and compile the denoiser inside the diffusers pipeline;
- I tested to compile the forward function of the denoiser instead (ie the call function of the unet or transformer), but the inference is not accelerated;
- I tested the inference time for 50 denoising steps on a Flux-8B-freepik model on a L40S GPU and obtained $23.63s$. After Bnb quantization, this number increases to $28.48s$. After quantization+compilation, we can reduce this number to $23.69s$;
- Note that the default compilation (ie capturing the full graph) will raise an error on a bnb-quantized …
> feat: enable bnb with torch compile

- pyproject.toml
full installation of pruna contained the dependancy autoawq twice, so removed one
Uninstalled pruna&autoawq and reinstalled both via installing pruna[full]
> chore: remove a double dependency when installing pruna[full]

- pyproject.toml
This PR bumps the version number to `v0.2.2`.
> build: bump version number to `v0.2.2`

- .github/workflows/external_contributions_tests.yaml
- .github/workflows/internal_contributions_tests.yaml
- .github/workflows/linting.yaml
- pyproject.toml
This PR introduces cached virtual environments to the internal CPU tests and the linting workflow. In short, the workflow creates a poetry "lock" file which specifies the *exact* versions of all installed packages. This lock file is then hashed and the cache of virtual environments is checked for a hit. In case of a hit, the cached environment is loaded and the workflow continues. In case of a miss, it falls back to an old environment and does updates where necessary. Finally, in case of a miss, the new environment is uploaded under a new hash.
In short, this reduces the "setup time" of a workflow from 2.5 minutes to 1 minute, of which 30 seconds are used to create the lock file and 30 seconds are used to retrieve the cached files. In my understanding, using uv would speed up specifically …
> ci: cache poetry installation

- src/pruna/engine/load.py
- src/pruna/engine/utils.py
- src/pruna/evaluation/metrics/metric_memory.py
This PR fixes a bug in the GPUMemory metric where two models are kept on the GPU at the same time. While this does not affect the correctness of the memory measurement, it can lead to OOM issues with models like e.g. Flux despite the model fitting on the GPU (as we are keeping it twice).
None.
Executed the metric on a previously failing Flux model.
None.
> fix: `GPUMemory` metric memory bug

- src/pruna/data/pruna_datamodule.py
This PR quickly adjusts the logging when checking the dataset <-> `collate_fn` check happens.
before:
```
INFO - Using max_seq_len of tokenizer: None
INFO - Testing compatibility with functools.partial(<function text_generation_collate at 0x7f340cc3e8c0>, tokenizer=GPT2TokenizerFast(name_or_path='facebook/opt-125m', vocab_size=50265, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '</s>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, …
```
> fix: `collate_fn` compatibility check logging

- pyproject.toml
This PR fixes a bug from #70, which excludes python 3.12 from the installation (even though we support it).
None.
None.
None.
> fix: python version specification in `pyproject.toml`

- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/compilation/utils.py
This PR makes the kv cache dynamic and the user doesnt need to worry about defining this anymore. It also means we are using the most efficient kv cache possible.
None.
Unit tests + notebook.
We should remove batch size and cache_size after this change.
> fix: make kv cache dynamic based on input

- docs/user_manual/save_load.rst
- src/pruna/engine/load.py
- src/pruna/engine/save.py
- src/pruna/engine/utils.py
This PR aims to eliminate a common error, where the base model is loaded in a specific precision but the user forgets to specify this precision again when loading the smashed model. This can also lead to wrong results for the `GPUMemory` metric. 
Generally I've updated the documentation to remove guidance on loading arguments, as the most important arguments are covered:
- torch_dtype is handled automatically now based on the base model
- device is handled via the smash config device (even though in the future, for multi-gpu support, this has to be improved)
- other arguments like e.g. deactivating the safety checked for image generation are automatically ported to the new model
None.
Tested by running:
```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer …
```
> feat: automate loading arguments

- src/pruna/algorithms/batching/ifw.py
- src/pruna/algorithms/batching/ws2t.py
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/quantization/gptq_model.py
- src/pruna/algorithms/quantization/quanto.py
- src/pruna/config/smash_config.py
- src/pruna/evaluation/evaluation_agent.py
- tests/config/test_smashconfig_data.py
This PR refactors the usage of a batch size arguments for various methods. The user now sets the expected inference batch size once in the SmashConfig and this is used throughout the algorithms. The batch_size hyperparameters in the algorithms are deprecated accordingly. Additionally, I deprecated the naming of `max_batch_size` and renamed it to `batch_size`, as "max" might be misleading.
None.
Ran tests for all affected methods and tested the deprecation locally - works as intended.
None.
> feat: `max_batch_size` refactoring

- src/pruna/config/smash_config.py
- src/pruna/smash.py
This PR moves the checks on whether data/tokenizers/processors are present to the `smash` function, so that people can specify them in any order during configuration setup, but are still informed before the smashing begins.
Tests fail at the moment as this PR already adheres to the renaming of `.data` in #67 , this PR will be merged tomorrow.
None.
Tested warnings for non-accepted configs locally.
None.
> refactor: move argument compatibility checks

- src/pruna/algorithms/caching/deepcache.py
- src/pruna/algorithms/caching/fastercache.py
- src/pruna/algorithms/caching/pab.py
- src/pruna/engine/model_checks.py
- tests/algorithms/test_combinations.py
- tests/algorithms/testers/caching.py
- tests/fixtures.py
This PR adds the PAB and FasterCache algorithms from diffusers (https://huggingface.co/docs/diffusers/main/api/cache).
I manually tested both caching mechanisms across all supported Diffusers pipelines, visually inspected the resulting images, videos, and measured the inference time (relative speedups match [this benchmark](https://github.com/huggingface/diffusers/pull/9562). For FLUX, I evaluated every supported combination of algorithms. I implemented new tests for each algorithm and all of their combinations with other algorithms.
I tried to make these cachers work with compilation but ran into errors. The main problem is that these methods introduce a condition for the attention layer, which hinders compilation.
> feat: add fastercache and pab

- src/pruna/config/smash_config.py
This should align the config keys we pass to the ConfigSpace, with the actually available algorithms and warn or inform if that is not the case. 
Fixes #116
> fix: enhance algorithm group management in SmashConfig when loading old configs

- src/pruna/algorithms/caching/fora.py
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/factorizing/qkv_diffusers.py
- src/pruna/algorithms/quantization/torchao.py
- tests/algorithms/testers/quantization.py
This PR introduces torchao as an additional quantizer for diffusion transformer models (e.g., FLUX). When combined with torch.compile, torchao delivers significant inference speedups for FLUX:
- Baseline (no optimization): 16 s
- torch.compile: 12.2 s
- torchao + torch.compile: 9.5 s
All timings were measured on an L40S GPU. Full benchmark (including visual comparison) are available [here](https://pruna.notion.site/torchao-bench-1ee70a039e5f80f88007d577e5fd4229?pvs=4).
The implementation closely follows the [diffusers-torchao](https://github.com/sayakpaul/diffusers-torchao) repository, which includes additional benchmarks and tests for the CogVideoX-5b video model.
- Added a dedicated algorithm test
- Manually tested all quantization modes on FLUX, both with and without torch.compile.
- …
> feat: add torchao quantizer

- src/pruna/algorithms/compilation/c_translate.py
- src/pruna/config/smash_config.py
- src/pruna/engine/handler/handler_diffuser.py
- src/pruna/engine/handler/handler_inference.py
- src/pruna/engine/handler/handler_standard.py
- src/pruna/engine/handler/handler_transformer.py
- src/pruna/engine/pruna_model.py
- src/pruna/engine/utils.py
- src/pruna/evaluation/evaluation_agent.py
- src/pruna/evaluation/metrics/metric_cmmd.py
- src/pruna/evaluation/metrics/metric_elapsed_time.py
- src/pruna/evaluation/metrics/metric_energy.py
- src/pruna/evaluation/metrics/metric_memory.py
- src/pruna/evaluation/metrics/metric_model_architecture.py
- src/pruna/evaluation/metrics/metric_torch.py
- src/pruna/evaluation/metrics/registry.py
- src/pruna/evaluation/task.py
- tests/algorithms/test_combinations.py
- tests/engine/test_device.py
- tests/evaluation/test_cmmd.py
Before, running the following code on CPU would fail because it was being forced on CUDA.
```python
from pruna.evaluation.metrics import CMMD
CMMD()
```
Fixes #108
> feat: improve overall device placement handling

- src/pruna/algorithms/caching/deepcache.py
- src/pruna/algorithms/caching/fastercache.py
- src/pruna/algorithms/caching/pab.py
- src/pruna/algorithms/compilation/c_translate.py
- src/pruna/algorithms/compilation/stable_fast.py
- src/pruna/algorithms/pruna_base.py
- src/pruna/algorithms/pruning/torch_structured.py
- src/pruna/algorithms/quantization/hqq.py
- src/pruna/algorithms/quantization/hqq_diffusers.py
- src/pruna/engine/load.py
- src/pruna/engine/save.py
- src/pruna/smash.py
This PR extends the algorithm base class to wrap any `import_algorithm_packages` definition as soon as a subclass is instantiated. It then provides a streamlined error with an informative message, if possible, referencing the documented installation.
None.
Verified locally that the function is wrapped and provides the appropriate error message.
- [ x My code follows the style guidelines of this project
None.
> feat: streamline import failure handling

- src/pruna/engine/load.py
- src/pruna/evaluation/metrics/metric_pairwise_clip.py
- src/pruna/evaluation/metrics/metric_torch.py
- src/pruna/evaluation/metrics/registry.py
- tests/engine/test_load.py
- tests/evaluation/test_task.py
There was a tiny error with pro-active device assignment in case of `TorchMetric` classes.
Fixes #168
> fix: 168 bug device placement does not work with torchmetric

- src/pruna/smash.py
This PR adjusts the order of compatibility checks in the smash function. The order should be that first, we check that the user has chosen the right interface (might need pruna_pro for some algorithms) and then attempt the import of required packages.
None.
Ran compatibility tests locally.
None.
> fix: move import check after availability checks

- src/pruna/engine/utils.py
- tests/engine/test_device.py
- Improved support for CUDA and MPS devices by allowing device indices (e.g., "cuda:0").
- Added validation for CUDA device indices to ensure they are within available range, with appropriate warnings for invalid requests.
- Updated MPS handling to always return "mps:0" since it only supports one device.
- Introduced a new test to verify device handling with indices, ensuring fallback behavior works as expected.
> fix: enhance device handling in set_to_best_available_device function

- README.md
This PR changes the displayed contributors in the Github readme to be the one automatically generated by Github. This is mainly done to acknoledge our great external contributors!
> docs: change contributors list

- src/pruna/algorithms/quantization/torchao.py
The quant type "fp8dqrow" was not working. This fix makes this option work for GPUs with CUDA Compute Capability >= 8.9 (e.g., L40S, H100). 
Run the algorithms with quant type "fp8dqrow" and "int8dq". Tested the combination with torch.compile and without it.
> fix: fix fp8dqrow setting

- src/pruna/config/smash_config.py
- src/pruna/engine/load.py
- src/pruna/engine/save.py
- src/pruna/engine/utils.py
- tests/engine/test_load.py
- tests/engine/test_save.py
This pull request enhances type flexibility across multiple files by replacing `str` with `Union[str, Path]` for file path parameters. This change enables functions to accept both string-based paths and `Path` objects from the `pathlib` module, improving compatibility and usability. The `pathlib.Path` module has also been imported wherever necessary.
Fixes #49
Linked Pruna Pro PR: https://github.com/PrunaAI/prunatree/pull/129
* Unit tests run:
* `test_save.py`
* `test_load.py`
> refactor: update function signatures to accept both str and Path types

- .github/workflows/cpu_tests.yaml
- .github/workflows/linting.yaml
- docs/contributions/how_to_contribute.rst
- pyproject.toml
The `tests` and `dev` extras were nearly identical, with only minor differences. To reduce redundancy and simplify the setup process for contributors, I've merged the tests dependencies into the `dev` group and removed the tests extra entirely.
Let me know if you'd prefer to keep them separate for any reason.
> feature: simplify the setup (tests + dev = dev)

- SECURITY.md
Small update of the security.md file : 
-> Add the github official documentation for details about reporting
-> Remove the Electron attribution, as the file is now following more standard structure
> chore: add github documentation on privately reporting vulnerabilities

- .github/actions/setup-uv-project/action.yml
- .github/workflows/installation.yaml
- pyproject.toml
This PR fixes:
- missing system specification for the bits and bytes packages
- the installation configuration for the GitHub actions, causing too many pings on the pruna pythonanywhere
None.
Installation tests pass now, so do mypy tests.
None.
> build: fix MacOS installation issues with bnb and `uv` index resolution

- src/pruna/algorithms/caching/deepcache.py
- src/pruna/algorithms/caching/fastercache.py
- src/pruna/algorithms/caching/fora.py
- src/pruna/algorithms/caching/pab.py
- src/pruna/algorithms/factorizing/qkv_diffusers.py
- src/pruna/algorithms/quantization/half.py
- src/pruna/algorithms/quantization/llm_compressor.py
- src/pruna/algorithms/quantization/torchao.py
This PR unlocks several algorithms for base models that are distributed with `accelerate`.
None.
Enabling accelerate automatically unlocks accelerate algorithm tests, which all pass locally.
None.
> feat: extend `accelerate` compatibility

- pyproject.toml
This PR extends the newly introduced pytest configuration in the `pyproject.toml` with the `duration` argument, which helps us keep track of the computation time on some experiments. Specifically for the CPU tests run on GitHub action, we will use this to determine which tests will be marked as `pytest.mark.slow`, meaning they will only run during the nightly tests.
None.
Verified updated logging locally.
None.
> tests: add `durations` argument to pytest config

- tests/fixtures.py
This PR makes use and replace the `JanusForConditionalGeneration` by a `AutoModelForImageTextToText` : in case there is a package version mismatch, only the Janus test would fail with some model-not-available-error.
The previous PR #145 on janus introduced some test that yields import error if the `transformers` is outdated.
Local test on Janus pass
> fix: change janus import into automodel import

- .github/workflows/stale.yaml
This PR introduces a nightly workflow that checks all open PRs and marks those with no progress for more than 10 days as stale. This will help keep track of older PRs.
None.
> ci: add nightly workflow to mark PRs as stale

- docs/user_manual/customize_metric.rst
- docs/user_manual/evaluate.rst
- src/pruna/evaluation/metrics/metric_torch.py
- src/pruna/evaluation/metrics/utils.py
- tests/evaluation/test_torch_metrics.py
This PR adds support for the arniqa image quality metric. Since ARNIQA uses an internal dataset, it now runs with the new call_type="y" (output-only).
> feat: add arniqa

- pyproject.toml
- src/pruna/evaluation/metrics/metric_torch.py
- src/pruna/evaluation/metrics/result.py
- tests/evaluation/test_torch_metrics.py
This PR integrates the CLIP-IQA metric from torchmetrics.
> feat: clipiqa metric

- pyproject.toml
- src/pruna/evaluation/metrics/metric_sharpness.py
- tests/evaluation/test_sharpness.py
- Adds SharpnessMetric, which computes focus via the variance of the Laplacian (higher = sharper). 
- CPU‑side numpy/OpenCV implementation.
You can use the `SharpnessMetric` directly or via the EvaluationAgent:
```
from pruna.evaluation.metrics.metric_sharpness import SharpnessMetric
from pruna.evaluation.task import Task
from pruna.evaluation.evaluation_agent import EvaluationAgent
from pruna.data.pruna_datamodule import PrunaDataModule
metric = SharpnessMetric(kernel_size=5)
inputs, gts = next(iter(my_dataloader))          # your B×C×H×W tensors
outputs = my_model(inputs)
metric.update(inputs, gts, outputs)
print("Sharpness:", metric.compute().result)     # higher = sharper
dm = PrunaDataModule.from_string("LAION256")
dm.limit_datasets(10)
task = Task(
request=["sharpness"],        # or …
```
> feat: add sharpness metric

- src/pruna/evaluation/metrics/metric_elapsed_time.py
- src/pruna/evaluation/metrics/metric_memory.py
- src/pruna/evaluation/metrics/metric_model_architecture.py
- src/pruna/evaluation/metrics/metric_torch.py
- src/pruna/evaluation/metrics/utils.py
- src/pruna/evaluation/task.py
- tests/evaluation/test_energy_metrics.py
- tests/evaluation/test_inference_time_metrics.py
- tests/evaluation/test_model_architecture_metrics.py
Removed deprecated:
-  stateless metrics
- metric modes for GPU memory metric
-  initialisation option with explicit call types
> chore: remove deprecated metrics, metric modes and calltypes

- README.md
- docs/user_manual/configure.rst
- pyproject.toml
- src/pruna/algorithms/caching/fora.py
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/kernels/__init__.py
- src/pruna/algorithms/kernels/flash_attn3.py
- src/pruna/algorithms/quantization/torchao.py
- src/pruna/config/smash_space.py
- tests/algorithms/test_combinations.py
- tests/algorithms/testers/__init__.py
- tests/algorithms/testers/kernels.py
- tests/fixtures.py
In this PR, we make use of HuggingFace's kernel hub to utilize flash attention 3 in diffusers pipelines where possible. Importantly, diffusers is refactoring their attention handling right now, hence we have two different implementations. 
In the current diffusers version, we wrap the call of a pipeline to intercept each call to `torch.nn.funcional.scaled_dot_product_attention`. If shapes, dtype and keyword arguments can be supported by flash attention, we reroute the computation to the fa3 kernel.
In the newer diffusers version (0.35.0, unreleased so far), we can register a new attention backend that calls the native attention or fa3 on the same criteria.
Overall, the speedup is minor for T2I pipelines but is substantial for Video Gen pipelines, in particular Wan.
None.
Added algorithm …
> feat: add `flash_attention 3` kernel for diffusers pipelines

- src/pruna/algorithms/batching/ws2t.py
- src/pruna/algorithms/compilation/c_translate.py
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/compilation/utils.py
- src/pruna/algorithms/pruna_base.py
- src/pruna/algorithms/quantization/gptq_model.py
- src/pruna/algorithms/quantization/hqq.py
- src/pruna/algorithms/quantization/huggingface_llm_int8.py
- src/pruna/algorithms/quantization/llm_compressor.py
- src/pruna/algorithms/quantization/torchao.py
- src/pruna/engine/load.py
- src/pruna/engine/model_checks.py
- src/pruna/engine/save.py
- src/pruna/evaluation/metrics/metric_energy.py
- src/pruna/telemetry/metrics.py
- tests/algorithms/test_combinations.py
- tests/fixtures.py
- Added functions to identify transformers pipelines for causal language models, sequence-to-sequence models, and speech recognition.
- Updated various quantization and compilation algorithms to utilize the new model checks, allowing for better integration with transformers pipelines.
- Introduced new test fixtures for transformers pipelines in the test suite to ensure comprehensive coverage.
```python
from transformers import pipeline
from pruna import smash, PrunaModel, SmashConfig
for algo in [("compiler", "torch_compile"), ("quantizer", "hqq")]:
model_name = "HuggingFaceTB/SmolLM2-360M-Instruct"
pipe = pipeline(
task="text-generation",
model=model_name,
)
print(pipe("Hello, how are you?"))
smash_config = SmashConfig(device="cuda")
smash_config[algo[0]] = algo[1]
smashed_pipe = …
```
> feat: enhance model checks for transformers pipelines

- README.md
- docs/user_manual/configure.rst
- docs/user_manual/smash.rst
- src/pruna/algorithms/batching/ws2t.py
- src/pruna/data/__init__.py
- src/pruna/data/datasets/audio.py
- src/pruna/engine/pruna_model.py
- tests/algorithms/test_combinations.py
- tests/fixtures.py
This PR updates the `pruna` tests in the following ways:
- smaller audio dataset: for better tutorial quality and faster tutorial tests, we use a smaller audio snippet for whisper tests
- segmind: segmind is not maintained and does not work with the newer diffusers version + deepcache, we update the tutorial to use sdxl instead
> tests: update audio datasets, add sdxl as example model

- src/pruna/engine/load.py
This PR does a little fix
When using torch.load, always load to cpu first and then move to target device.
Problem when loading to the device directly was, that every tensor within a pipeline e.g. was moved to cuda, also some which are not supposed to be - not every pipeline can handle this unexpected device (e.g. SanaPipeline)
By loading to cpu first and then moving to target device, we make sure that only the right parts are moved to the target_device
Every test which is using torch.load has been re-run and is successful
> torch.load always to cpu first

- src/pruna/algorithms/factorizing/qkv_diffusers.py
- src/pruna/engine/model_checks.py
The current main branch in `diffusers` is undergoing a large refactorization for attention computation.
The attention processors still exist but Flux and Wan have now a local version of their own processor. Also qkv fusing was changed: it is now taking place in the AttentionMixin class (not anymore in the transformer class itself).
Sister PR in pruna_pro is [here](https://github.com/PrunaAI/prunatree/pull/197).
The combination qkv_diffusers+torch_compile is taking forever to compute on the latest diffusers codebase
Tested on Flux-dev with diffusers==0.34.0 and diffusers==0.35.0dev0
On Flux-dev, the generation time goes from 10.44s (original) to 5.12s (with `qkv_diffusers`+`fp8`+`torch_compile`).
The warm-up time (first inference) takes 56.16s.
> fix: make qkv compatible with torch.compile in next diffusers release

- src/pruna/algorithms/quantization/hqq_diffusers.py
- src/pruna/engine/load.py
- src/pruna/engine/save.py
AutoHQQ class will only take care of nn.linear for saving/loading. While it has no impact on sd or flux models, this can introduce bugs for models that have additional nn.Parameters (eg Sana), or buffers, etc.
The code changes are made of:
- small additional line in load.py to let the user specify the dtype of the backbone in the pipeline (when loading with .from_pretrained for Sana, the dtype was set to float32, and re-used for the hidden_state's type after);
- wraps of the `save_quantized` and `from_quantized` (autoHQQ will put non linear layers to meta device, so we need to save it before hand. After loading, we need to put back all parameters and buffers thare are on meta to the device with the saved values instead).
Fixes #273 
Notebook for reproducing is accessible …
> fix: hqq diffusers saving and loading forget non linear layers

- docs/user_manual/smash.rst
This PR adjust the tutorial on smashing by limiting the dataloaders for a reduced execution time when this is run during the documentation tests.
> docs: limit execution time of smash tutorial

- docs/tutorials/index.rst
- docs/tutorials/target_modules_quanto.ipynb
- docs/user_manual/target_modules.rst
- docs/utils/gen_docs.py
- src/pruna/algorithms/quantization/quanto.py
- src/pruna/config/target_modules.py
Add documentation for target modules:
- a documentation page target_modules.rst, referenced as a drop-down from SmashConfig
- change printed hyperparameters so that TargetModules are correctly shown on the algorithm page
- provide a documentation_name_with_link attribute in target modules to easily link to the doc in algorithms
- add a target modules tutorial with demonstration on quanto
Building the documentation
I think an other documentation page about how to use the `map_targeted_nn_roots` function would have its place somewhere in the "Customize components" section, but this is left for an other PR
> docs: add target modules documentation

- README.md
Fixed the incorrect GitHub clone link in the README.  
Changed:  
`git clone https://github.com/pruna-ai/pruna.git`  
to  
`git clone https://github.com/PrunaAI/pruna.git`
N/A
- Verified that the corrected link successfully clones the repository.
The previous clone link returned a 404 error.
> docs: fix incorrect clone link in README
