- README.md
This PR fixes the links to the sections Telemetry, Algorithms and Contributions in the Pruna README.
None.
Tested with the newest version on Github.
None.
> fix: links README for telemetry, algorithms and contributions

- README.md
This PR adjusts the build and test badges - by adjusting the workflow targets to include a .yaml file ending.
None.
Verified this with the Readme version on GitHub.
None.
> fix: build and test workflow badges

- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/pruna_base.py
- src/pruna/algorithms/pruning/torch_structured.py
- src/pruna/data/datasets/text_generation.py
- src/pruna/evaluation/metrics/metric_energy.py
> fix: typos in descriptions and logging

- CONTRIBUTING.md
- docs/contributions/how_to_contribute.rst
This PR adds the CONTRIBUTING file recognized by GitHub and updates the contribution workflow with a guide on forking the repository.
None.
Previewed the CONTRIBUTING file on GitHub and verified the documentation on readthedocs.
None.
> docs: add `CONTRIBUTING` file and update contribution workflow

- src/pruna/data/pruna_datamodule.py
Quick cleaning for classmethods that mixed the self and cls conventions
This is only style so no tests were added, tests pass
> style: clean cls implicit argument in PrunaDataModule

- SECURITY.md
This PR adds the guide for reporting security issues as recommended by GitHub. The appropriate security settings for the repository have already been enables. In short, this guide and the according settings allow to safely report security-critical bugs and issues for the pruna repository.
None.
None.
None.
> docs: add `SECURITY.md` guide

- docs/tutorials/flux_small.ipynb
This PR updates the outdated flux tutorial using quanto to hqq_diffusers instead.
None.
Notebook and test run successfully.
None.
> docs: update flux tutorial notebook from quanto to hqq

- docs/utils/gen_docs.py
- src/pruna/algorithms/quantization/gptq_model.py
This PR fixes a bug in the documentation generation of the GPTQ installation instructions.
None.
Ran the documentation generation locally - you can also verify this in the workflow outputs.
None.
> fix: installation documentation GPTQ special case

- docs/tutorials/evaluation_agent_cmmd.ipynb
- pyproject.toml
- tests/documentation/test_tutorials.py
This PR updates the version of the package from `v0.2.0post1` to `v0.2.1`.
None.
None.
None.
> build: bump version to `v0.2.1`

- src/pruna/engine/pruna_model.py
- src/pruna/engine/utils.py
- tests/fixtures.py
This PR fixes several issues in evaluating LLMs, related to model compatibility, particularly with compressed or quantized models. The changes ensure smoother evaluation for:
- Models compressed using ipex-llm
- Models compressed using quanto + xFast
- smolLMs and Microsoft’s phi models 
- Quantized models that previously failed with `.to()`
> fix: fix inference issues for LLM evals

- .pre-commit-config.yaml
- docs/user_manual/evaluation.rst
Fixed outdated / broken links in our documentation.
Also fixes the bugs in our pre-commit file. 
Fixes #73
> fix: broken links docs

- docs/tutorials/portable_compilation.ipynb
- pyproject.toml
- src/pruna/algorithms/batching/ws2t.py
- src/pruna/algorithms/compilation/c_translate.py
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/pruning/torch_structured.py
- src/pruna/algorithms/quantization/hqq.py
- src/pruna/config/smash_config.py
- src/pruna/engine/load.py
- src/pruna/engine/save.py
- tests/documentation/test_tutorials.py
This PR prepares for the release of torch 2.7 which supports portable compilation. It includes extensions to the loading and saving mechanisms for torch compile and adds a tutorial to guide users through this new feature.
None.
Added a tutorial notebook which is included in the tests.
For any guidance on how to use this feature, please refer to the tutorial.
> feat: support portable torch compilation

- src/pruna/algorithms/compilation/stable_fast.py
- src/pruna/engine/model_checks.py
This PR introduces the following changes:
- Adds new model checking functions.
- Enables support for Comfy models when combining caching with the `stable-fast` compilation mode.
- **Comfy models are not compatible with `stable-fast` alone.** With this change, Comfy models can only be used in combination with caching mechanisms from `Pruna_pro`. Direct usage of `stable-fast` without caching will not work for these models.
- Since model checking for Comfy models is not straightforward, we tag the model passed from Comfy with a custom attribute `is_comfy`  upon creation. We use that tag for identification. 
Tested alongside the new cache refactoring by running Comfy locally on both Flux and SD models.
> feat: add comfy support sfast

- pyproject.toml
This PR bumps the version of pruna to v0.2.3
> build: bump version to `v0.2.3`

- pyproject.toml
For the new integration with Hugging Face, we need to update the `hf-xet` storage. 
Fixes #94
> chore: update `huggingface-hub` dependency to version `>=0.30.0` with extras `hf-xet`

- pyproject.toml
This PR lower-bounds the version of ConfigSpace to the most recent version to ensure compatibility.
#86 
Tested the installation locally.
None.
> fix: lower-bound ConfigSpace version

- src/pruna/algorithms/quantization/hqq_diffusers.py
- src/pruna/algorithms/quantization/huggingface_diffusers_int8.py
> fix: fastercache and pab compatibility

- src/pruna/algorithms/caching/fora.py
- src/pruna/algorithms/compilation/stable_fast.py
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/quantization/hqq_diffusers.py
- src/pruna/algorithms/quantization/huggingface_diffusers_int8.py
- tests/algorithms/test_combinations.py
- tests/algorithms/testers/caching.py
Add FORA caching for FLUX pipelines. 
I tested all algorithm combinations for FLUX [dev]. I did a visual evaluation of the outputs and speedups. I tested the `set_params`, `enable` and `disable` methods of the cache helper. I implemented an integration test and combination tests, which all pass locally.
I did not add a tutorial for this new feature yet as there will be a tutorial for all recently added cachers including FORA, PAB, and FasterCache.
> feat: add fora cacher

- src/pruna/config/smash_config.py
This PR removes the following interfaces, for which we have added a deprecation warning since `v0.2.0` and which we will now remove:
```python
smash_config["cachers"] = "deepcache" # no more plural algorithm groups
```
```python
smash_config["cacher"] = ["deepcache"] # no more lists as algorithms
```
```python
smash_config["cache_deepcache"] = 1 # no more algorithm group prefix for hyperparameters
```
None.
Tested locally that the removed interfaces no longer work.
None.
> refactor: remove deprecated algorithm names

- docs/user_manual/configure.rst
- src/pruna/engine/utils.py
- tests/algorithms/testers/base_tester.py
- tests/common.py
This PR fixes a bug in the memory cleanup function by removing the destruction of objects from the function.
None.
Ran the tests that were failing as a consequence of this locally.
None.
> fix: memory cleanup bug

- pyproject.toml
This PR bumps the version number of pruna.
> release: bump version to `v0.2.4`

- tests/algorithms/testers/quantization.py
This PR fixes the following two bugs in the algorithm testing setup:
- torchao now supports stable diffusion pipelines, but the rejection models in the tester class did not reflect this yet
None.
Reran the failing tests locally.
None.
> fix: torchao rejection test

- .github/workflows/internal_contributions_tests.yaml
- pyproject.toml
- src/pruna/algorithms/quantization/gptq_model.py
- tests/documentation/test_tutorials.py
> tests: add nightly tests

- src/pruna/engine/utils.py
- tests/engine/test_device.py
This reverts commit 097d4adf29512412266826538b6862aa8b01ed30 in order to have the tests running for the next release.
> Revert "fix: enhance device handling in set_to_best_available_device function (#171)"

- README.md
- docs/user_manual/configure.rst
- src/pruna/algorithms/compilation/torch_compile.py
- src/pruna/algorithms/pruna_base.py
This PR extends the README and documentation to discuss the new algorithm group "distributers".
None.
None.
None.
> feat: introduce `distributers`

- pyproject.toml
This PR bumps the version of `pruna` to `v0.2.6`.
> build: update version to `v0.2.6`

- .github/workflows/documentation.yaml
> ci: update algorithm generation workflow

- src/pruna/algorithms/compilation/utils.py
- src/pruna/data/pruna_datamodule.py
This PR contains fixes for breaking changes that happened in the new transformers release.
> fix: handle new transformers version

- pyproject.toml
This PR bumps the pruna version to `v0.2.8`
> build: bump pruna version to `v0.2.8`

- docs/contributions/how_to_contribute.rst
- docs/contributions/open_an_issue.rst
- docs/tutorials/index.rst
- docs/user_manual/configure.rst
- docs/user_manual/customize_algorithm.rst
- docs/user_manual/customize_dataset.rst
- docs/user_manual/customize_metric.rst
- docs/user_manual/evaluate.rst
- docs/user_manual/save_load.rst
- docs/user_manual/smash.rst
Handles several updates related to the GTM updates in prunatree. https://github.com/PrunaAI/prunatree/pull/199/ See that PR for the docs URL.1
> docs: updates gtm
